### ISSUE TITLE
what is the ratio of train_size/val_size?

### ISSUE THREAD

**Issue by geek-APTX4869** [mczhuge/ICON#16]
dear author:
  训练集和验证集如何划分呢?或者说训练集和验证集的大小比是多少

**Comment by mczhuge** [comment]
验证集就是用了测试集中比较小的3个数据集，不参与训练。
目前都是直接这么用的。

**Comment by mczhuge** [comment]
@geek-APTX4869 请参考这里，自行定义你想要的验证集。
https://github.com/mczhuge/ICON/blob/main/util/evaltool/run_sod_valid.sh
