### ISSUE TITLE
downloading checkpoints from Baidu

### ISSUE THREAD

**Issue by alessiocaporali** [mczhuge/ICON#3]
Hi,
could be possible to host the checkpoints on a different place?
Alessio

**Comment by mczhuge** [comment]
Thanks for your concern. I will upload them into google drive in recent days.

**Comment by mczhuge** [comment]
Dear Alessio,

I have uploaded them.

- Datasets: 
* [Goole Drive](https://drive.google.com/file/d/1aHYvxXGMsAS0yN4zhKt8kKorVL--9bLu/view?usp=sharing)
- Checkpoints: 
* [Goole Drive](https://drive.google.com/file/d/1wcL8n3lSc1pswMfDYCOBQJJjwnuhWdwK/view)

Hope this could help you,
MC
