### ISSUE TITLE
A mistake in ICE

### ISSUE THREAD

**Issue by Dawn-bin** [mczhuge/ICON#4]
hi, I have read your code, and I find a mistake in ICE modules [L165](https://github.com/mczhuge/ICON/blob/c6c3fe062f519f73f8fde593f21eff983caea1dd/main/model/icon/modules.py#L165).

```
in2 = F.interpolate(in1, size=in1.size()[2:], mode='bilinear')
```
I think it should correct like below:
```
in2 = F.interpolate(in2, size=in1.size()[2:], mode='bilinear')
```

**Comment by mczhuge** [comment]
Thank you so much. It seems truly a mistake during tiding up my code. I invite you as a contributor.
