### ISSUE TITLE
we meet some erro

### ISSUE THREAD

**Issue by wutongmengyao** [mczhuge/ICON#5]
File "D:/pydemo/ICON/main/train.py", line 226, in <module>
    train(dataset, parser)
  File "D:/pydemo/ICON/main/train.py", line 130, in train
    for step, (image, mask) in enumerate(loader):

TypeError: 'NoneType' object is not callable

**Comment by mczhuge** [comment]
Apologies for the delay! This indicates an image or mask file is missing. I recommend printing the name and double-checking!

**Comment by mczhuge** [comment]
Hi, @wutongmengyao . Have you solved this problem?
