### ISSUE TITLE
predicted saliency map

### ISSUE THREAD

**Issue by NazilaPourhaji** [mczhuge/ICON#6]
Hi, 
Is it possible to upload the predicted saliency map into Google Drive?
I can't download them.

**Comment by mczhuge** [comment]
I sincerely apologize for this. I check BaiduDisk from my location, which is also slow because I am not currently in China. I'll make an effort to upload them recently!

**Comment by mczhuge** [comment]
@ModelPruning  You can also find them in [Google Drive](https://drive.google.com/file/d/1TMWJsWs-bKCAvCkCnugwiEgJPx9WlNdC/view) now.

**Comment by BaharehAsheghi** [comment]
> @ModelPruning You can also find them in [Google Drive](https://drive.google.com/file/d/1TMWJsWs-bKCAvCkCnugwiEgJPx9WlNdC/view) now.

Hi,
the link doesn't work.
Please correct it.

**Comment by mczhuge** [comment]
My colleague accidentally deleted it by mistake and I asked him to re-upload it.

**Comment by Shi-Wm** [comment]
> > @ModelPruning You can also find them in [Google Drive](https://drive.google.com/file/d/1TMWJsWs-bKCAvCkCnugwiEgJPx9WlNdC/view) now.
> 
> Hi, the link doesn't work. Please correct it.

We have re-uploaded Prediction Maps, you can  find them in [Goole Drive](https://drive.google.com/file/d/16_H322xYPAJ2RY35Gam3Y9bB6ctLJowr/view?usp=sharing) now.

**Comment by BaharehAsheghi** [comment]
> > > @ModelPruning You can also find them in [Google Drive](https://drive.google.com/file/d/1TMWJsWs-bKCAvCkCnugwiEgJPx9WlNdC/view) now.
> > 
> > 
> > Hi, the link doesn't work. Please correct it.
> 
> We have re-uploaded Prediction Maps, you can find them in [Goole Drive](https://drive.google.com/file/d/16_H322xYPAJ2RY35Gam3Y9bB6ctLJowr/view?usp=sharing) now.

Thank you so much.
