### ISSUE TITLE
About predicted saliency map of HKU-IS in ICON-R

### ISSUE THREAD

**Issue by xuanli98** [mczhuge/ICON#7]
Thanks for your great work. I downloaded the predicted saliency map of  ICON-R. However, there are only 4445 predicted saliency maps in HKU-IS, instead of 4447. Would you like to provide the full predicted saliency maps of HKU-IS. Thank you very much.

**Comment by mczhuge** [comment]
Sorry, we also find this mistake before.  It seems that many projects share the same problem. Actually, it does not inflect the performance in HKU-IS.

**Comment by xuanli98** [comment]
Thanks for your response. I have another question: can I fairly compare the performance of each model as long as I use the same evaluation code to evaluate the saliency prediction maps provided by each work? Is it fair to the performance of each model under different numbers of prediction maps?

**Comment by mczhuge** [comment]
Q1) can I fairly compare the performance of each model as long as I use the same evaluation code to evaluate the saliency prediction maps provided by each work?
A1: Yes, if you want to compare the maps given by each work, you should evaluate them under **the same evaluation code**.

Q2) Is it fair to the performance of each model under different numbers of prediction maps?
Actually, not fair! But missing 2 figures will not inflect the performance much, unless there is a deliberate selection of the worst.

**Comment by xuanli98** [comment]
> Q1) can I fairly compare the performance of each model as long as I use the same evaluation code to evaluate the saliency prediction maps provided by each work? A1: Yes, if you want compare the maps given by each work, you should evaluate them under the same code.
> 
> Q2) Is it fair to the performance of each model under different numbers of prediction maps? Actually, not fair! But missing 2 figures will not inflect the performance much, unless there is a deliberate selection of the worst.

Thanks for your response !
